### PR TITLE
IOS-XR: Add traceroute()

### PR DESCRIPTION
**Pull request by mirceaulinic**
Implements https://github.com/napalm-automation/napalm-base/pull/17

### CODE REVIEW

**Comment by dbarrosop** [comment]
I merged `napalm-base` and re-run the test. However, they are still failing, can you check? There seems to be some conflicts as well.

**Comment by mirceaulinic** [comment]
Error due to copy-paste in the test base. Needs https://github.com/napalm-automation/napalm-base/pull/20 merged before re-testing.

**Comment by dbarrosop** [comment]
Damn it! I merged this one and the test was failing still. Could you take a look?

https://travis-ci.org/napalm-automation/napalm-iosxr/builds/126914905

**Comment by mirceaulinic** [comment]
@dbarrosop Could you please retrieve it and let me have a look? This we we can avoid the conflicts with get_users() and merge it. Thanks!

**Pull request merged**
