### PR TITLE
Refactored get_facts()

### PR DESCRIPTION
**Pull request by mirceaulinic**
In pair with https://github.com/napalm-automation/napalm-iosxr/pull/25, to use the XML agent instead of retrieving raw text output.
Fixes https://github.com/napalm-automation/napalm-iosxr/issues/16 (https://github.com/napalm-automation/napalm/issues/56).
Dependency: https://github.com/napalm-automation/napalm-base/pull/54

### CODE REVIEW

**Comment by dbarrosop** [comment]
This one seems to be failing.

**Comment by mirceaulinic** [comment]
Yeah... as always forgot to provide mock data. Why am I not wondering? 😠

**Comment by dbarrosop** [comment]
Next time you test on your fancy routers remember all the poor people that can't afford and IOSXR ;)

**Comment by mirceaulinic** [comment]
I would rather call them rich / happy :P

**Comment by mirceaulinic** [comment]
Pushed mock, failure again caused by `get_bgp_neighbors_detail`

**Pull request merged**
