### PR TITLE
Version 0.4.7

### PR DESCRIPTION
**Pull request by mirceaulinic**
<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Releasing to include the changes from https://github.com/napalm-automation/napalm-iosxr/pull/94

**Comment by mirceaulinic** [comment]
@ogenstad we'll need to make sure this is consistent with `eos` (the other driver implementing this method - for `junos` it's not required). Could you please add a note under https://github.com/napalm-automation/napalm-base/blob/develop/napalm_base/base.py#L465 to tell that neighbours that don't belong to a group can be found under the `_` key? Thanks!

**Comment by ogenstad** [comment]
@mirceaulinic, sure I can take a look at that. I'm not that familiar with Junos, does all neighbors belong to a group there or why isn't it a problem on Junos?

**Comment by mirceaulinic** [comment]
Yes @ogenstad on Junos the neighbours must belong to a group.

**Comment by dbarrosop** [comment]
+1

**Pull request merged**
