### PR TITLE
Move to Pytest

### PR DESCRIPTION
**Pull request by ogenstad**
Basic framework and one passing test.

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Fantastic! Let me know if you need any help! ;)

**Comment by mirceaulinic** [comment]
Anything else you'd like to add here @ogenstad?

**Comment by ogenstad** [comment]
This is ready for review now. I made quite a lot of assumptions that the current mock data were producing the desired results.

Also I had to make some small changes to the get_route_to and cli functions.

**Review by mirceaulinic — APPROVED** [review]
LGTM

**Comment by dbarrosop** [comment]
Great! Thx again!

**Pull request merged**
