### PR TITLE
Release 0.4.3

### PR DESCRIPTION
**Pull request by mirceaulinic**
<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

### CODE REVIEW

**Comment by mirceaulinic** [comment]
@ogenstad @dbarrosop any idea what tox is complaining about? https://travis-ci.org/napalm-automation/napalm-iosxr/jobs/187217399

`coverage.misc.CoverageException: --include and --source are mutually exclusive` is the exception message.

And it seems to be similar to https://travis-ci.org/napalm-automation/napalm-base/jobs/187104868 in napalm-base.

**Comment by dbarrosop** [comment]
looks like some conflicting configuration option but I have no idea where those are coming from:
```
coverage.misc.CoverageException: --include and --source are mutually exclusive
```

**Comment by ogenstad** [comment]
Think it might be this: https://bitbucket.org/ned/coveragepy/issues/541/coverage-43-breaks-nosetest-with-coverage. Looks like they just released coverage 4.3.1. Perhaps you can restart the Travis run and try again?

**Comment by mirceaulinic** [comment]
That's it @ogenstad! Tack!

**Comment by ogenstad** [comment]
@mirceaulinic nice to see that you're practicing your Swedish. 😉

**Comment by mirceaulinic** [comment]
Haha @ogenstad - I'm trying (without succeeding) to learn few other languages 😆 Especially when I don't exclude Sweden as a potential future destination.

**Pull request merged**
