### PR TITLE
use sisqo for device connection instead of netmiko

### PR DESCRIPTION
**Pull request by wasabi222**
This is a rewrite of the current iosxr_ssh driver implemented using the sisqo library for ssh connections, which issues commands and receives responses much quicker than the current implementation. Currently only get_facts is implemented but I'll be writing more methods soon.

### CODE REVIEW

**Comment by dbarrosop** [comment]
Hi,
thanks for the PR, before proceeding let's have a wider discussion though. I haven't heard of this library before and there are a few reasons to use netmiko:

1. Kirk, the author of netmiko, is active in the napalm project which has many advantages.
2. netmiko has support for a wide variety of devices which means we get one lib to manage lots of different devices which is convenient as we have many people working on many drivers, so the less libraries we use the easiest it gets to go from one driver to another.
3. netmiko is quite mature, it has ~50 contributors, thousands of commits...

For those reasons it would be nice to have a wider discussion first.

@ktbyers @mirceaulinic 

Thanks again
David

**Comment by ktbyers** [comment]
Adding a few comments...

1. I think for automation we should prioritize reliability over performance especially in screen-scraping contexts. There are reliability tradeoffs in going faster. In that your screen-scraping starts to break.

2. This is not to say performance is to be neglected, but I would pretty much always want to emphasize reliability over performance (while giving people capabilities to go faster if they want to try).

3. The `sisqo` project is very immature. Thirty-seven commits; single author, no testing/CI process. Also it is Cisco only.


Personally, I don't want to manage two screen-scraping libraries (heck I am not sure I want to manage one :-) ). 

I think it probably should be rejected just from the how new the library is. How few contributors there are on it. And the consequentially how narrow the testing will be on it.

I also think there is some meaningful risk in that it is not using Paramiko and looks to be tying more into the operating system and subprocess (on quick glance).

**Comment by wasabi222** [comment]
I'm leaving for vacation for 10 days in just a few hours so I won't be able to participate much in the discussion for a bit, so I'd like to walk through my reasoning ahead of time, which will hopefully foster further discussion.

First, I agree with you that using netmiko is preferable to introducing another library, and I started to write methods on the iosxr_ssh driver as it is currently implemented, but there seemed to be many inconsistencies issuing commands via the cli versus using the xml agent. Using the CLI, some commands would come back with no output (show inventory rack), some commands would need to be sent twice to get output (show configuration running-config domain name), and all commands were slow to execute and get data from. This is in contrast with the newer library, where issuing commands gives consistent output without having to resend commands, and receives output 3 times faster than the current implementation (via timeit). 

From an end-user perspective, this would be transparent to them, with them not needing to know the underlying library responsible for implementing the methods.

From a dev perspective, the methods would be implemented similar to the nxos_ssh or ios drivers, with commands being issued via the `_send_command` method and then parsed, so any dev working on those drivers or similar shouldn't have an issue jumping between drivers. There also doesn't appear to be anything specific to netmiko being used in the iosxr_ssh driver currently (like how FileTransfer and InLineTransfer from netmiko are used in the ios driver), and instead it's just acting as an underlying connection. I still think using netmiko would still make sense if there were not issues relating to output consistency and speed, however that is not the case. Instead, I believe it is best to use whatever transport is the most reliable.

**Comment by ktbyers** [comment]
@wasabi222 It sounds like there are three issues:

1. Reliably getting output from Netmiko for IOS-XR. If it is not reliably returning output, we should fix that. It is probably easy to fix. Please open issues on this, I am not aware of open issues on this for Netmiko.

2. The performance. I don't think the 3x performance matters much, but people can work on that if they want to. There are pretty easy ways in Netmiko to go faster (note, this is in conflict to issue 1 though). I say it doesn't matter much because you can pretty easily parallelize to N devices where N is a pretty large number. So for example, people have used netmiko + threads with 1200 devices and netmiko + some form of async with 6000 devices.

3. XMLAgent vs CLI - If Netmiko is reliably returning data, then this is an IOS-XR issue or a NAPALM issue and would be the case regardless of the underlying library.

```
From an end-user perspective, this would be transparent to them, with them not 
needing to know the underlying library responsible for implementing the methods.
```

Except for all the other untested things that this change breaks for end-users (there are lots and lots of different versions of IOS-XR out there and Netmiko has almost certainly been tested on a wider set of them). 

A bigger issue is all the ongoing maintenance problems for NAPALM project (i.e. managing two screen-scraping libraries including one that is just in its infancy and that has one contributor). The project only has three commits since Jan 10.

Note, I think all screen-scraping libraries will probably run into issues #1 and #2. I think it is fundamentally inherent in the problem (that the communication channel has no definitive notion of being done). There are likely better and worse ways to solve the problems, but the problems don't go away (this will be the same for sisqo library).

That being said, I definitely am open to better ways of solving these issues, so I think we should try to improve things in Netmiko. 

We should definitely fix issue 1 (i.e. if data is not being reliably gathered). Also I am hoping in the fall to simplify some of the Netmiko timeouts which should make it significantly easier to speed up performance.

**Comment by wasabi222** [comment]
Hi Kirk, thanks for the quick reply.

I have not contributed significantly to napalm so I'm not very familiar with some of the things you're referencing. Can you help clarify these?

```
Except for all the other untested things that this change breaks for end-users (there are lots and lots of different versions of IOS-XR out there and Netmiko has almost certainly been tested on a wider set of them).
```
 When you say netmiko has been tested on a wider code range, what testing are you referring to? My understanding is that netmiko is simply the transport and tests would occur on the napalm methods - unless you're referring to the testing of expected prompts in order to stop receiving output? 

```
A bigger issue is all the ongoing maintenance problems for NAPALM project (i.e. managing two screen-scraping libraries
```
I apologize, I'm not familiar with these ongoing maintenance problems you mention. Are you saying that a bug in a secondary library would need to be addressed in order to fix (for instance) a getter that breaks in napalm, and as such, would require more general overhead?  Is the idea here that all maintainers can dev on all drivers, and would rather not introduce a new library?

Ultimately, as long as the output is reliable (and preferably quick) I'm okay with using any library. Just to clarify though, the speed issues I'm referencing are to a connection to a single device ie sending a command on two separate lines takes upwards of 8 seconds: 4 for the first `_send_command` and then an additional 4 for the second call. 

I'm happy to open an issue in netmiko for the reliability issue in the meantime. Are you (or is anyone) aware of active development on this driver? I would love to contribute as I'm in need of a reliable iosxr driver and the XML agent is not the best.

**Comment by ktbyers** [comment]
@wasabi222 Netmiko is an independent library and is used widely outside of NAPALM. 

So there are all the users of Netmiko on IOS-XR directly; there are also current users of NAPALM + IOS-XR using xml agent. 

You are saying there are transport issues, but I am not aware of those issues...so please report the issues you are seeing.

There is this recent issue which I need to fix and I know what the cause is:

https://github.com/ktbyers/netmiko/issues/553

There also is some line repainting issue on IOS-XR issue, but I think that is a pretty narrow issue and I think unlikely to be affecting you.

So in general the testing I am referring to is:
1. Netmiko unit tests which include testing against IOS-XRv device.
2. NAPALM unit tests against real devices
3. Netmiko field use
4. NAPALM field use

My points on the maintenance have multiple angles...1) there is a reasonable chance we would have to fork sisqo and start maintaining it. We already have this situation with a similar library (pyfg). 2) I doubt sisqo has been widely tested so I expect it has lots of issues, that we would have to fix (in the context of getting it to work properly on napalm-iosxr) which parenthetically are probably going to slow it down meaningfully, and 3) we would have to keep maintaining it across time (i.e. we would have to keep fixing things in both Netmiko and in sisqo) to address issues that arise in NAPALM.

```
Ultimately, as long as the output is reliable (and preferably quick) I'm okay with using any library. Just to clarify though, the speed issues I'm referencing are to a connection to a single device ie sending a command on two separate lines takes upwards of 8 seconds: 4 for the first _send_command and then an additional 4 for the second call.
```

Why does the 8 seconds matter to you? When you can do 100 devices or 500 devices in the same 8 seconds (there are some caveats here for devices that fail, but still general point holds). 

Also have you tried using Netmiko timers to speed this up?

Note, in the fall, I hope to implement a `send_command_list()` which will execute a list of show commands in succession and should be more rapid for multiple show commands.

```
Are you (or is anyone) aware of active development on this driver? I would love 
to contribute as I'm in need of a reliable iosxr driver and the XML agent is not the best.
```

Both Netmiko on IOS-XR and napalm-iosxr are actively being developed. @mirceaulinic knows a lot more than I ever care to know about XML agent and its issues. Note, the issues in XML agent are generally Cisco problems and not fundamentally NAPALM or Netmiko problems.

**Comment by alexforster** [comment]
I heard somebody mentioned my library :)

@ktbyers The fundamental problem with netmiko is that it strips VT100 opcodes rather than emulating them. I did that too, for a while, but IOS-XR is unique among Cisco products in that it produces complex VT100 sequences that need to be processed in order to get sane output. I put a lot of effort into trying to avoid going this route, but I just found myself writing a terminal emulator.

I don't know if it's the right direction for napalm to take, and I agree that you'd probably want to bring this into napalm rather than depend on me to maintain it forever, but fwiw it's actually just [a single short-ish file](https://github.com/alexforster/sisqo/blob/v2.1.1/sisqo/ssh.py) as long as you don't need the separate Cisco config parsing functionality. I've put a lot of work into making it accurately reproduce exactly what you'd expect to see in a terminal session without any platform-specific workarounds. It has 2+ years of heavy production use, and as long as you don't use the aforementioned config parsing functionality, it's tested & working with Juniper, Arista, etc – supporting any given platform should just boil down to fixing up the prompt matching regex.

**Comment by ktbyers** [comment]
@alexforster Thanks for the extra information.

Can you provide more details on why can't just strip the ANSI escape codes with IOS-XR? I haven't really seen significant issues with this in practice (although on other platforms).

**Comment by dbarrosop** [comment]
> Are you saying that a bug in a secondary library would need to be addressed in order to fix (for instance) a getter that breaks in napalm, and as such, would require more general overhead?

That can happen as with any other project. 

> Is the idea here that all maintainers can dev on all drivers, and would rather not introduce a new library?

As with any big project you have many people working on many parts of the project so doing things differently in different parts will lead to mistakes, maintainers having troubles going from one driver to another, etc. so it's preferable to reuse libs and tools.

**Comment by mirceaulinic** [comment]
I have been following this discussion and I heard good arguments from both parties.

> The fundamental problem with netmiko is that it strips VT100 opcodes rather than emulating them. I did that too, for a while, but IOS-XR is unique among Cisco products in that it produces complex VT100 sequences that need to be processed in order to get sane output. I put a lot of effort into trying to avoid going this route, but I just found myself writing a terminal emulator.

@alexforster I am certainly not a subject expert, but could you please expand on this topic and provide some examples eventually? I have been using netmiko with iosxr for quite a long time and I didn't notice weird things like that (note: I don't claim it's not possible, it is possible, but I just didn't see anything). There are plenty of problems, but they were mainly related to the bloody XML agent.

Also note that at the time being, netmiko is used indirectly, via pyiosxr: https://github.com/fooelisa/pyiosxr/blob/master/pyIOSXR/iosxr.py: that library simply connects to the device via SSH and executes `xml` on the command line to enter in XML mode, and from there on it simply writes and reads XML documents via SSH.
So the only difference of the pure SSH-driver vs. the existing one (based on the XML API) is in terms of the shape of the documents you read/write, i.e., unstructured vs. XML -- that's all, that doesn't have any directly implications on the transport channel. So if there are no transport issues with the existing driver, there shouldn't be any issues with the pure SSH driver.

Going back to the previous idea: you claim there are issues, and despite the fact that nobody reported them yet (it is very true there aren't many napalm-iosxr users out there), we believe you.
In this case I would do the following: the [`CiscoXrSSH` class from netmiko](https://github.com/ktbyers/netmiko/blob/master/netmiko/cisco/cisco_xr_ssh.py) inherits the `write_channel `, `read_channel `, et al, methods from the [`BaseConnection`](https://github.com/ktbyers/netmiko/blob/master/netmiko/base_connection.py); why not override these methods in `CiscoXrSSH` with the enhanced code you have under https://github.com/alexforster/sisqo/blob/v2.1.1/sisqo/ssh.py -- this would be a very nice addition to netmiko, helping the existing users, and also helping us, the napalm maintainers.

Cheers,
-Mircea

**Comment by mirceaulinic** [comment]
Ping @alexforster and @wasabi222 - checking in here: did you see my comment above?

**Comment by wasabi222** [comment]
Thanks for checking back in - I will submit an issue with pyiosxr now. Unfortunately, I don't have much else to add here. I'm going to close this out.

**Comment by ktbyers** [comment]
@wasabi222 The starting point is to flag the relevant issues in Netmiko (i.e. what is actually not working). Up to this point, no one has referenced an actual issue of something not working.

All that raising an issue in pyiosxr is going to do is to re-hash the same thing in that forum as opposed to here.

**Comment by ktbyers** [comment]
@wasabi222 Thanks for creating this issue: https://github.com/napalm-automation/napalm-iosxr/issues/151

That is helpful...

**Pull request closed without merging**
